### ISSUE TITLE
Deciphering Commands For operation

### ISSUE THREAD

**Issue by superfckkk** [rkargon/pixelsorter#10]
Hey dude, still getting the ropes of using Python Modules for glitching. 

Reading thru the documentation and I'm having a hard time getting the command to work as I see it in the docs:

Invoked python3 in terminal

Then:

pixelsort.py '/Users/User/Documents/DESIGN/VisualVice2077/BP9KeaOCIAAZRuG.jpeg' -o '/Users/User/555.jpeg'

File "<stdin>", line 1
    pixelsort.py '/Users/User/Documents/DESIGN/VisualVice2077/BP9KeaOCIAAZRuG.jpeg' -o '/Users/User/555.jpeg'
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax

Got this error, then I did this:

pixelsort.py /Users/User/Documents/DESIGN/VisualVice2077/BP9KeaOCIAAZRuG.jpeg -o /Users/User/555.jpeg
  File "<stdin>", line 1
    pixelsort.py /Users/User/Documents/DESIGN/VisualVice2077/BP9KeaOCIAAZRuG.jpeg -o /Users/User/555.jpeg
                                                                                                                       ^
SyntaxError: invalid imaginary literal

Now, I'm kinda stuck here.

**Comment by chinatsu** [comment]
if i understand you correctly, you enter the commands after entering the python interpreter runtime? i think you'll find slightly better results if you run `python3 pixelsort.py '/Users/User/Documents/DESIGN/VisualVice2077/BP9KeaOCIAAZRuG.jpeg' -o '/Users/User/555.jpeg'` in a terminal (outside of python)
